name: MessagePlugin
version: '${project.version}'
main: me.kriotix.messageplugin.MessagePlugin
api-version: '1.20'
commands:
  msg:
    Description: "Message other players."

  r:
    Description: "Reply to a conversation.""